
-- IBM DB2 database schema for an retail store database with ANSI SQL DDL followed by Data for the necessary tables

-- Create the table for customers
CREATE TABLE customer (
  customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL,
  PRIMARY KEY (customer_id)
);

-- Create the table for products
CREATE TABLE product (
  product_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
  product_name VARCHAR(100) NOT NULL,
  description VARCHAR(500) NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  PRIMARY KEY (product_id)
);

-- Create the table for orders
CREATE TABLE orders (
  order_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
  customer_id INTEGER NOT NULL,
  order_date DATE NOT NULL,
  PRIMARY KEY (order_id),
  FOREIGN KEY (customer_id) REFERENCES customer (customer_id)
);

-- Create the table for order_items
CREATE TABLE order_item (
  order_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
  order_id INTEGER NOT NULL,
  product_id INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  PRIMARY KEY (order_item_id),
  FOREIGN KEY (order_id) REFERENCES orders (order_id),
  FOREIGN KEY (product_id) REFERENCES product (product_id)
);

-- Insert sample data into the customer table
INSERT INTO customer (first_name, last_name, email)
VALUES 
  ('John', 'Doe', 'john.doe@email.com'),
  ('Jane', 'Doe', 'jane.doe@email.com');

-- Insert sample data into the product table
INSERT INTO product (product_name, description, price)
VALUES 
  ('T-Shirt', 'A plain T-Shirt', 19.99),
  ('Jeans', 'A pair of blue jeans', 49.99);

-- Insert sample data into the orders table
INSERT INTO orders (customer_id, order_date)
VALUES 
  (1, '2023-01-01'),
  (2, '2023-01-02');

-- Insert sample data into the order_item table
INSERT INTO order_item (order_id, product_id, quantity)
VALUES 
  (1, 1, 2),
  (2, 2, 1);
