-- ORACLE database schema for an airline database with ANSI SQL DDL followed by Data for the necessary tables

-- CREATE TABLE FOR AIRLINE
CREATE TABLE AIRLINE (
  AIRLINE_ID NUMBER PRIMARY KEY,
  AIRLINE_NAME VARCHAR2(255) NOT NULL,
  AIRLINE_CODE VARCHAR2(10) NOT NULL,
  AIRLINE_COUNTRY VARCHAR2(255) NOT NULL
);

-- CREATE TABLE FOR AIRCRAFT
CREATE TABLE AIRCRAFT (
  AIRCRAFT_ID NUMBER PRIMARY KEY,
  AIRLINE_ID NUMBER NOT NULL,
  AIRCRAFT_NAME VARCHAR2(255) NOT NULL,
  AIRCRAFT_MODEL VARCHAR2(255) NOT NULL,
  AIRCRAFT_CAPACITY NUMBER NOT NULL,
  CONSTRAINT FK_AIRCRAFT_AIRLINE FOREIGN KEY (AIRLINE_ID) REFERENCES AIRLINE(AIRLINE_ID)
);

-- CREATE TABLE FOR FLIGHT
CREATE TABLE FLIGHT (
  FLIGHT_ID NUMBER PRIMARY KEY,
  AIRLINE_ID NUMBER NOT NULL,
  AIRCRAFT_ID NUMBER NOT NULL,
  FLIGHT_NUMBER VARCHAR2(255) NOT NULL,
  DEPARTURE_CITY VARCHAR2(255) NOT NULL,
  ARRIVAL_CITY VARCHAR2(255) NOT NULL,
  DEPARTURE_DATE DATE NOT NULL,
  ARRIVAL_DATE DATE NOT NULL,
  CONSTRAINT FK_FLIGHT_AIRLINE FOREIGN KEY (AIRLINE_ID) REFERENCES AIRLINE(AIRLINE_ID),
  CONSTRAINT FK_FLIGHT_AIRCRAFT FOREIGN KEY (AIRCRAFT_ID) REFERENCES AIRCRAFT(AIRCRAFT_ID)
);


INSERT INTO airlines (name, headquarters, established) VALUES
  ('Delta Airlines', 'Atlanta, GA', '1924-05-30'),
  ('United Airlines', 'Chicago, IL', '1926-04-06');

INSERT INTO flights (airline_id, departure_airport, arrival_airport, departure_time, arrival_time) VALUES
  (1, 'Atlanta, GA', 'Los Angeles, CA', '2022-07-01 12:00:00', '2022-07-01 16:00:00'),
  (1, 'Atlanta, GA', 'London, UK', '2022-07-01 18:00:00', '2022-07-02 10:00:00'),
  (2, 'Chicago, IL', 'New York, NY', '2022-07-01 12:00:00', '2022-07-01 14:00:00');

INSERT INTO passengers (first_name, last_name, passport_number, nationality) VALUES
  ('John', 'Doe', 'A12345678', 'United States'),
  ('Jane', 'Doe', 'B12345678', 'Canada');

INSERT INTO bookings (flight_id, passenger_id, seat_number) VALUES
  (1, 1, 'A1'),
  (2, 2, 'B2');
